package com.log4om.android.data.adif

import com.log4om.android.data.model.Qso
import java.time.format.DateTimeFormatter

object AdifWriter {

    private val DATE_FMT = DateTimeFormatter.BASIC_ISO_DATE
    private val TIME_FMT = DateTimeFormatter.ofPattern("HHmmss")

    fun toAdif(qsos: List<Qso>): String = buildString {
        append("ADIF generated by Log4OM Android\n")
        appendField("ADIF_VER", "3.1.4")
        appendField("PROGRAMID", "Log4OM Android")
        appendField("PROGRAMVERSION", "1.0")
        append("<EOH>\n\n")
        qsos.forEach { q ->
            appendRecord(q)
            append("<EOR>\n\n")
        }
    }

    private fun StringBuilder.appendRecord(q: Qso) {
        appendField("CALL", q.callsign)
        appendField("QSO_DATE", q.qsodate.toLocalDate().format(DATE_FMT))
        appendField("TIME_ON", q.qsodate.toLocalTime().format(TIME_FMT))
        appendField("BAND", q.band)
        appendField("MODE", q.mode)
        if (q.freq > 0) appendField("FREQ", khzToMhz(q.freq))
        if (q.freqrx > 0) appendField("FREQ_RX", khzToMhz(q.freqrx))
        appendField("RST_SENT", q.rstsent)
        appendField("RST_RCVD", q.rstrcvd)
        appendField("NAME", q.name)
        appendField("QTH", q.qth)
        appendField("COUNTRY", q.country)
        if (q.dxcc > 0) appendField("DXCC", q.dxcc.toString())
        q.cqzone?.let { appendField("CQZ", it.toString()) }
        q.ituzone?.let { appendField("ITUZ", it.toString()) }
        appendField("GRIDSQUARE", q.gridsquare)
        appendField("CONT", q.cont)
        appendField("COMMENT", q.comment)
        appendField("NOTES", q.notes)
        appendField("STATION_CALLSIGN", q.stationcallsign)
        appendField("MY_GRIDSQUARE", q.mygridsquare)
        appendField("MY_NAME", q.myname)
        appendField("MY_RIG", q.myrig)
        appendField("MY_COUNTRY", q.mycountry)
        q.mydxcc?.takeIf { it > 0 }?.let { appendField("MY_DXCC", it.toString()) }
        appendField("OPERATOR", q.operator)
        q.txpwr?.takeIf { it > 0 }?.let { appendField("TX_PWR", it.toString()) }
        appendField("PROP_MODE", q.propmode)
        appendField("CONTEST_ID", q.contestid)
        appendField("SAT_NAME", q.satname)
        appendField("SAT_MODE", q.satmode)
        appendField("ADDRESS", q.address)
        appendField("EMAIL", q.email)
        appendField("STATE", q.state)
        appendField("CNTY", q.cnty)
        appendField("QSL_VIA", q.qslvia)
        appendField("QSL_MSG", q.qslmsg)
        appendField("PFX", q.pfx)
        appendField("CLASS", q.classField)
        appendField("SRX_STRING", q.srxstring)
        appendField("STX_STRING", q.stxstring)
        appendField("SOTA_REF", q.sotaRef)
        appendField("IOTA", q.iota)
        appendField("POTA_REF", q.potaRef)
        appendField("WWFF_REF", q.wwffRef)
        q.lat?.let { appendField("LAT", it.toString()) }
        q.lon?.let { appendField("LON", it.toString()) }
        q.distance?.let { appendField("DISTANCE", it.toString()) }
    }

    private fun StringBuilder.appendField(name: String, value: String?) {
        if (value.isNullOrBlank()) return
        append("<").append(name).append(":").append(value.length).append(">")
        append(value)
        append('\n')
    }

    private fun khzToMhz(khz: Double): String {
        val mhz = khz / 1000.0
        return if (mhz == mhz.toLong().toDouble()) mhz.toLong().toString()
        else mhz.toString()
    }
}
